### ISSUE TITLE
sub_process_class was removed

### ISSUE THREAD

**Issue by Tseplyaev** [JuDFTteam/aiida-fleur#114]
@broeder-j 
I have commented out the use of sub_process_class in eos workchain in attempt to fix the tests. 
Please have a look at this when you have time.

**Comment by broeder-j** [comment]
The change is fine. 
The only point of that line was to know which sub_process failed, i.e the message would have contained some information (uuid, pk, class) of what failed. In this case i am not sure if this even still worked, because I adapted the message already.
