### ISSUE TITLE
Replace ``BaseRestartWorkChain`` with implementation in ``aiida-core``

### ISSUE THREAD

**Issue by janssenhenning** [JuDFTteam/aiida-fleur#131]
At the moment the used implementation of BaseRestartWorkChain is inside the aiida-fleur repository. However, there is an implementation of this workchain in aiida-core. At some point we should probably switch to the one in aiida-core.

Is anyone aware of major differences between the two implementation (besides slighly different variable/method names)

**Comment by Tseplyaev** [comment]
No, I think there are should be no large differences. This is due to historical reasons: we copied this function from QE before it became available in aiida-core. After that the function itself changed a bit in aiida-core, but I had never time to rewrite this in aiida-fleur
