### ISSUE TITLE
Fleurinp Data should also initialize with relative paths for files

### ISSUE THREAD

**Issue by broeder-j** [JuDFTteam/aiida-fleur#16]

**Comment by broeder-j** [comment]
There might be a bug in the plugin, because somewhere the path of the file might be altert and 
This should work, but does not.
inpxml = '../inp_xml_files/CuBulkXML/files/inp.xml'
a = os.path.abspath(inpxml)
os.path.isfile(a)

**Comment by broeder-j** [comment]
This might actually very hard, up to impossible to do. since it is not clear from were the method is called. It can know its own file path and therefore all file_path within aiida-fleur. I guess there is a reason why Aiida single file data does not allow for it. Therefore this is first a won't fix. But a method should be provided to the user to early get the abs_path for the fleurinp init.

**Comment by Tseplyaev** [comment]
Since aiida_core 1.0.0b, it is not recommended to use absolute paths.
Now there is a possibility to initialise a FleurinpData via:

```
from aiida_fleur.data.fleurinp import FleurinpData
FleurinpData(files=['inp.xml'], node=FolderDataNode)
```

i.e. specifying a file name and a FolderData node.
