### ISSUE TITLE
Fleur_convergence workflow should always terminate and store the error if calculation fails 

### ISSUE THREAD

**Issue by broeder-j** [JuDFTteam/aiida-fleur#17]
currently if a calculation inpgen or fleur fails in the scf workflow, the workflow will fail at a later point if it tries to access these files. Therefore make checks if calculation finished else terminate in a controlled way.

**Comment by broeder-j** [comment]
This because was solved, by storing everything in the ctx. But since we create now the final node with an external workfunction, to get the provenance right, this issue is still there and became harder. figure out one can make a workfunction a class method (with some decorator or so), i.e to have the context available within the workfunction without creating extra nodes.

**Comment by Tseplyaev** [comment]
For now I see no clear solution to the problem of the outer CalcFunction generating WorkChain's output.
Except this problem, FleurScfWorkChain always manages to write at least something to the output Dict.
