### ISSUE TITLE
Error in Spin Spiral calculation

### ISSUE THREAD

**Issue by Sayan611** [JuDFTteam/aiida-fleur#193]
Dear Fleur Developers,
I was trying to do spin spiral scf calculation in fleur. In this attempt, I found an error while converging charge density for the nonzero value of q (qss= 0.1 0.0 0.0) which did not occur in the case of qss= 0.0 0.0 0.0
The error is:
"Intel MKL ERROR: Parameter 10 was incorrect on entry to ZGEMM"
I have attached the inp.xml and out file here. The error was being shown in the out file.
I will be grateful if you kindly help me in this matter.
Thank you.

Regards
Sayan Banik

[Files.zip](https://github.com/JuDFTteam/aiida-fleur/files/9508838/Files.zip)

**Comment by broeder-j** [comment]
Dear @Sayan611, Thanks for the report and thank you for using FLEUR. 
This is an error related to FLEUR, not to AiiDA-FLEUR, I therefore forwarded it to the FLEUR developers. 
Also I suggest you post you problem here: http://fleur.xobor.de/
the fleur user forum, there all FLEUR developers and other users will find it.

To reproduce the Error you encountered , which probably to do with parallelization more information will be helpful/need:

- How FLEUR was compiled, i.e. with which Libraries, which version of FLEUR (or the out.xml file if the info of this is there.)
- How the job of yours was executed, i.e. the execution command.
