### ISSUE TITLE
pypi release for aiida-core v2

### ISSUE THREAD

**Issue by chrisjsewell** [JuDFTteam/aiida-fleur#206]
As added in #202

**Comment by chrisjsewell** [comment]
In turn, this can then be released on https://github.com/conda-forge/aiida-fleur-feedstock

**Comment by janssenhenning** [comment]
@chrisjsewell Sorry for the delay, the 2.0 version is now on pypi the conda forge PR should appear shortly

**Comment by chrisjsewell** [comment]
Thanks 🙏
