### ISSUE TITLE
Bug SCF for magnetic systems

### ISSUE THREAD

**Issue by broeder-j** [JuDFTteam/aiida-fleur#21]
currently for magnetic systems we store the overall_charge and charge_density1 and charge_density2.

maybe this should become a list under one key charge_density. 
currently scf fails because it accesses charge_density. also the numbers do not seem right, check the parsing.

**Comment by broeder-j** [comment]
might be fixed by now. scf works for magnetic systems. I leave this open till I have checked how the output node looks in this case.

**Comment by broeder-j** [comment]
the parser runs, but the charge_density is none in some cases...

**Comment by Tseplyaev** [comment]
@broeder-j 
I faced the same problem a couple of weeks ago. Turns out scf workflow tried to get('charge dencity', None), failed and returned None. See if [this](https://github.com/Tseplyaev/aiida-fleur/commit/36dce5f68fa91501bab0603c0070ae3c70db2a62) fixes the problem.

**Comment by broeder-j** [comment]
@Tseplyaev I have done something similar on branch v0_12 https://github.com/JuDFTteam/aiida-fleur/blob/aiida_v0_12/aiida_fleur/workflows/scf.py .
But I have moved the try except into the conditions part. Because otherwise this might also lead to other errors. Also we want to keep the charge_distance_all key, it contains the information from all iterations. I leave this open until I have merged branch v_0_12 back into develop.

**Comment by Tseplyaev** [comment]
In develop branch, the SCF workchain tries to extract
`/fleurOutput/scfLoop/iteration/densityConvergence/overallChargeDensity/@distance` (should work for magnetic systems) and
`/fleurOutput/scfLoop/iteration/densityConvergence/chargeDensity/@distance` if previous failed (should work for non-magnetic systems).
