### ISSUE TITLE
add slurm option in workflow for inpgen

### ISSUE THREAD

**Issue by lokamani** [JuDFTteam/aiida-fleur#210]
@janssenhenning 

It would be nice to have the slurm parameters in workflows for inpgen:

For example including `account` option in scf.py

        options = {
            'max_wallclock_seconds': int(self.ctx.options.get('max_wallclock_seconds')),
            'resources': self.ctx.options.get('resources'),
            'queue_name': self.ctx.options.get('queue_name', ''),
            'account': self.ctx.options.get('account')
        }

**Comment by janssenhenning** [comment]
Hi @lokamani, I opened #211 to allow these inputs. I added `options_inpgen`, which accepts everything that goes into  `options` and will be passed on to the inpgen calculation

**Comment by lokamani** [comment]
works like a charm, thx
