### ISSUE TITLE
Add switch to workchains to run them in serial (no calcualtion submited in parallel)

### ISSUE THREAD

**Issue by broeder-j** [JuDFTteam/aiida-fleur#22]
This might be helpful, if one runs fleur on his computer and not an hpc resource. I am not sure how several openpi fleur versions started on the same machine influence each other.

**Comment by broeder-j** [comment]
So far there is a serial key for each workchain, but this only means no mpi for all code executions...

**Comment by Tseplyaev** [comment]
get_inputs_fleur, which is used in all the workchains that explicitly submit FleurCalculation, sets 
options['withmpi'] = False and options['resources'] = {"num_machines": 1}.
This implementation should work for PBS-like schedulers.
