### ISSUE TITLE
fleurinp methods buggy

### ISSUE THREAD

**Issue by broeder-j** [JuDFTteam/aiida-fleur#25]
The methods get_structure_data and get_kpoints_data_nwf currently fail with 

```
XMLSyntaxError: Element 'fleurInput', attribute 'fleurInputVersion': [facet 'enumeration'] The value '' is not an element of the set {'0.28', '0.27'}.
```

this is after the change to the new xml schema management. And should be fixed. Also the work functions of these should be working again.

**Comment by broeder-j** [comment]
xmlschema_doc = etree.parse(fleurinp._schema_file_path)
            xmlschema = etree.XMLSchema(xmlschema_doc)
            parser = etree.XMLParser(schema=xmlschema, attribute_defaults=True)
            tree = etree.parse(inpxmlfile)#, parser) # parser somewhat broken TODO, lxml version?  

This has to do that parsing with a parser generated by the schema, somehow fails. for now I disable parsing with schema, this is also in other places,... validation has to be done different, see fleurinpmod. I keep this open this this issue the schema parsing works.

**Comment by Tseplyaev** [comment]
get_kpointsdata_ncf and get_structuredata_ncf have unit tests, they work for verison 1.0.1.
However, the content of resulting KpointsData and StructureData is not yet tested.

**Comment by broeder-j** [comment]
We will implement full cycle round test with inpgen.
