### ISSUE TITLE
How the plugin uses the structure needs to be overworked

### ISSUE THREAD

**Issue by broeder-j** [JuDFTteam/aiida-fleur#31]
So far the  plugin assumes atoms at sites and does not care about weights or vacancies. There should be checks for the whole functionality of structureData and warnings/ignores if Fleur is unable to use certain structureDatas. Otherwise the Prov between different codes is at risk...

**Comment by broeder-j** [comment]
especially this should be tested together with KKR.
AiiDA now has the X element with 0 charge for empty spheres.
Until now the plugin is untested for such structures. There should be a test for these structure types.

**Comment by broeder-j** [comment]
@PhilippRue let me know if you run into any problems when using fleur and kkr side by side

**Comment by PhilippRue** [comment]
This is an example structure for a thin film calculation in KKR where the 'X' element is used for empty sites:
```
$ struc_Fe7Nb.extras
{'_aiida_hash': '028a276f32294cf6e7193ae09753e45b931be3d3c22e697cd94004378a51f746',
  'kkr_settings': {'RBLEFT': [-1.6584398382215, 0.0, -1.1726940557829],
   'NLBASIS': 1,
   'NRBASIS': 1,
   'RBRIGHT': [3.316879676443, 0.0, 33.521770110619],
   'ZPERIODL': [-1.6584398382215, 0.0, -2.3453881115658],
   'ZPERIODR': [1.6584398382215, 0.0, 2.3453881115658]}}

$ struc_Fe7Nb.cell
 [[3.3168796764431, 0.0, 0.0],
  [1.6584398382215, 2.3453881115923, 0.0],
  [0.0, 0.0, 32.349076054836]]

$ struc_Fe7Nb.sites
 [<Site: kind name 'X' @ 0.0,0.0,1.1726940557829>,
  <Site: kind name 'X' @ 1.6584398382215,0.0,3.5180821673487>,
  <Site: kind name 'X' @ 0.0,0.0,5.8634702789145>,
  <Site: kind name 'Fe' @ 1.6584398382215,0.0,8.2088583904803>,
  <Site: kind name 'Nb' @ 0.0,0.0,10.096376717551>,
  <Site: kind name 'Nb' @ 1.6584398382215,0.0,12.46832205832>,
  <Site: kind name 'Nb' @ 0.0,0.0,14.776062076428>,
  <Site: kind name 'Nb' @ 1.6584398382215,0.0,17.104053329552>,
  <Site: kind name 'Nb' @ 0.0,0.0,19.449441441171>,
  <Site: kind name 'Nb' @ 1.6584398382215,0.0,21.79482955279>,
  <Site: kind name 'Nb' @ 0.0,0.0,24.140217664356>,
  <Site: kind name 'X' @ 1.6584398382215,0.0,26.485605775921>,
  <Site: kind name 'X' @ 0.0,0.0,28.830993887487>,
  <Site: kind name 'X' @ 1.6584398382215,0.0,31.176381999053>]

$ struc_Fe7Nb.pbc
(True, True, False)
```

**Comment by broeder-j** [comment]
@PhilippRue  and this example fails for AiiDA-fleur? during Input generation, or in the Fleur call. i.e problem with the X or with the large vacuum?

**Comment by PhilippRue** [comment]
> @PhilippRue and this example fails for AiiDA-fleur? during Input generation, or in the Fleur call. i.e problem with the X or with the large vacuum?

I actually did not have time to test it. I just wanted to give you an example if you want to give it a try.

**Comment by broeder-j** [comment]
often we do natoms= len(n.sites), which would be false in the case of vacancies.

**Comment by broeder-j** [comment]
Inpgen has now these basic capabilities. see commit af6d5d5d45024cf103ff10c98255d48deebef9f5
