### ISSUE TITLE
Work Flow for relaxation

### ISSUE THREAD

**Issue by vamshimohank** [JuDFTteam/aiida-fleur#35]
Dear Jens, 

I am wondering if anyone is working on the structural relaxation workflow, if not I would like to make one. There seems to be a WF with old workflows but none in the new ones. Let me know so that I can start to work on it. 

Regards
Vamshi

**Comment by broeder-j** [comment]
You can start working on it. There were some changes in the newer Fleur versions, therefore I waited and never got back to it. 
Sorry I did not see the issue earlier, next time write me an email, or @broeder-j if I do not get back to you within two days.

**Comment by Tseplyaev** [comment]
In release v1.0.0a the FleurRelaxWorkChain is implemented.
It wraps structure optimisation implemented in FLEUR and does not provide additional structure analysis yet.
One can find some documentation in https://aiida-fleur.readthedocs.io/en/latest/user_guide/workflows/relax_wc.html
