### ISSUE TITLE
FLEUR parser wrong values for certain keys...

### ISSUE THREAD

**Issue by broeder-j** [JuDFTteam/aiida-fleur#43]
Check the keys:

- nspecies... 
- Walltime (should not be negative. probable because a day was in between and date handling is wrong)

**Comment by broeder-j** [comment]
also check nsymmetry in the case of one symmetry operation.

**Comment by Tseplyaev** [comment]
Since node.xpath (that is used in eval_xpath2) return always a list, nsymmetry should be always OK.
That is also true for number of species

@broeder-j could you add more details on the walltime problem? It seems to be ok from the first view
