### ISSUE TITLE
please fix dependencies

### ISSUE THREAD

**Issue by ltalirz** [JuDFTteam/aiida-fleur#52]
* `aiida-core >= 0.12.0[atomic_tools]` results in always selecting aiida-core 0.12.2 (even though 0.12.3 is out). I believe [the correct syntax should be](https://stackoverflow.com/a/36491124): `aiida-core[atomic_tools] >=0.12.0,<1.0`
 * please don't fix the numpy version as it is fixed by aiida-core

**Comment by ltalirz** [comment]
@broeder-j can you please make these two small changes and release a new version on pypi?
otherwise we'll need to exclude aiida-fleur from the next release of the aiidalab metapackage.

**Comment by broeder-j** [comment]
@ltalirz I did a new release version of the python 2.7 aiida-fleur in production with aiida-core 0.12.3 and uploaded it to pypi.
As soon is Vasily we finished debugging the workchains, for aiida-core > 1.0 there will be a python3 release. I hope that will do for now.

**Comment by ltalirz** [comment]
Thanks @broeder-j !
