### ISSUE TITLE
set_kpointsdata has to be moved to FleurinpModifier

### ISSUE THREAD

**Issue by Tseplyaev** [JuDFTteam/aiida-fleur#57]
FleurinpData.set_kpointsdata() is a CalcFunction which stores a new FleurinpData in the database. 
It does not actually change FleurinpData and should be moved to the FleurinpModifier

**Comment by broeder-j** [comment]
I agree, but maybe we should leave also a `set_kpointsdata()` function exposed on `FleurinpData` (for the (human) user it makes sense that this is how to do it), but internally create a `FleurinpModifier` with the instance and apply the kpoints to a new instance which is returned, by keeping the provenance right. But the base functionality to set the kpoints should go indeed into `FleurinpModifier`.

**Comment by Tseplyaev** [comment]
Yes, we might still need to have a method for `set_kpointsdata` in `FluerinpData`
but is not it better to teach a user the fact that *any* change to `FleurinpData` should be done via `FleurinpModifier`? Maybe it is not so user-friendly but enforces some structure to the code and it's logic.

**Comment by broeder-j** [comment]
Set_kpointsdata is now a method of FleurinpModifier
