### ISSUE TITLE
EOS WorkChain should enforce the constant MTradii  among all structures

### ISSUE THREAD

**Issue by Tseplyaev** [JuDFTteam/aiida-fleur#62]
If I understand correctly, it can happen that all the structures can have different MT radii. It has to be solved because one can not compare energies between structures having different MTradii.

**Comment by broeder-j** [comment]
The implementation <1.0.0a was flexible. If one parses calc_parameters (Dict) for inpgen these were enforced on ALL runs. If not the defaults for each structure was used. In general I would recommend as a user to always control the flapw parameters. Looking at the current implementation I think the same is still true if the exposed inputs parses the nodes through and not just the 'template'.
```
input_scf = AttributeDict(self.exposed_inputs(FleurScfWorkChain, namespace='scf'))
```
One can compare energies with different muffin-tin, with some uncertainty of course.

**Comment by broeder-j** [comment]
The same is through for local orbitals, it can happen that one scaling has different electronic setups than others. I suggest to make the run mode as follows: if user parses flapw parameter node enforce the usage of this one. If the user does not set the muffin-tin it there it is 'wanted' by the user to use the defaults (which might differ in the eos). If no parameter node is parsed. The workchain executes inpgen on the lowest scale structure, exports the flapw parameter of that inp.xml file and enforces these on all other scaling (this ensures the mt radii work for all scalings and the electron setup makes sense together with the muffin tin).

**Comment by broeder-j** [comment]
overall we should thik about the constructing of an optimize parameter workchain which will always be called in (nearlly all) fleur-workchains if no explicit calc parameter node is given. (instead of just an inpgen run and using the defaults)

**Comment by Tseplyaev** [comment]
@broeder-j 

You are right, I overlooked this. If one specifies wanted MT radii in the `calc_param` node it should work.
The only problem is when MTs overlap for compressed structure and not for the others.
However, I think it is not a big issue - if I remember correctly failed `ScfWorkChain`s will not be used for fitting and won't spoil the `EOS` workchain.
