### ISSUE TITLE
consider release for Quantum Mobile

### ISSUE THREAD

**Issue by ltalirz** [JuDFTteam/aiida-fleur#67]
@Tseplyaev @broeder-j 
I'm preparing a Quantum Mobile release, and fleur being included means it should ship with its AiiDA plugin.

I see that there has been a v1.0.0a release tagged in the repo but the latest release on pypi is still 0.6.3: https://pypi.org/project/aiida-fleur/

Could you please consider releasing it on pypi as well?
Given that there seems to have been quite a bit of activity since the 1.0.0a release, perhaps consider making a beta / 1.0 release as well?

**Comment by Tseplyaev** [comment]
Dear @ltalirz, 
I am sorry for late reply. I will prepare the 1.0.0a release on pypi this week.
Indeed, I have been working on some improvements before releasing next version but I think I will not be able to launch it before Christmas. For now, I plan to make it in mid-late January.

**Comment by ltalirz** [comment]
thanks for the update!

**Comment by Tseplyaev** [comment]
@ltalirz 
`pip install aiida-fleur==1.0.0a0` should work now.

I am not closing this issue till `aiida-fleur==1.0.0` is released on pypi.

**Comment by Tseplyaev** [comment]
On 31. January we made a AiiDA-Fleur release 1.1.0. It is already available on pypi.
