### ISSUE TITLE
Add schema validation for all files, inserted into inp.xml via XInclude

### ISSUE THREAD

**Issue by Tseplyaev** [JuDFTteam/aiida-fleur#91]
As I mentioned in the https://github.com/JuDFTteam/aiida-fleur/issues/89#issuecomment-694212912, `relax.xml` file is being validated if it is included to the initialiser of FleurinpData by inserting it into inp.xml.
However, I have realised that it works for `relax.xml` only due to some hard-coded filenames and xml paths.
This behaviour should be extended to all possible *.xml files (kpts.xml and others).

**Comment by janssenhenning** [comment]
This is implemented with #111
