### ISSUE TITLE
symmetry operations are not parsed completely into FleurinpData attributes

### ISSUE THREAD

**Issue by Tseplyaev** [JuDFTteam/aiida-fleur#94]
Symmetry operations from inp.xml rewrite each other because they have the same key in the dictionary. Note the absence of the identity sym operator

```  
'symmetryOperations': {'symOp': {'row-1': '-1 0 0 .0000000000',
    'row-2': '0 1 0 .0000000000',
    'row-3': '0 0 1 .0000000000'}}},
```

**Comment by broeder-j** [comment]
@anoopkcn now the symops are parsed as a list. 
It might be that there are other parts of the fleur inp.xml which are not parsed correctly. One should check this after the next fleur release because there where changes.
